//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chat.proto
// Note: requires additional types generated from: core.proto
namespace rsctrl.chat
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatLobbyInfo")]
  public partial class ChatLobbyInfo : global::ProtoBuf.IExtensible
  {
    public ChatLobbyInfo() {}
    
    private string _lobby_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lobby_id
    {
      get { return _lobby_id; }
      set { _lobby_id = value; }
    }
    private string _lobby_topic;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lobby_topic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lobby_topic
    {
      get { return _lobby_topic; }
      set { _lobby_topic = value; }
    }
    private string _lobby_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lobby_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lobby_name
    {
      get { return _lobby_name; }
      set { _lobby_name = value; }
    }
    private string _lobby_nickname;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lobby_nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lobby_nickname
    {
      get { return _lobby_nickname; }
      set { _lobby_nickname = value; }
    }
    private rsctrl.chat.LobbyPrivacyLevel _privacy_level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"privacy_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.chat.LobbyPrivacyLevel privacy_level
    {
      get { return _privacy_level; }
      set { _privacy_level = value; }
    }
    private rsctrl.chat.ChatLobbyInfo.LobbyState _lobby_state;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"lobby_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.chat.ChatLobbyInfo.LobbyState lobby_state
    {
      get { return _lobby_state; }
      set { _lobby_state = value; }
    }
    private uint _no_peers;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"no_peers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint no_peers
    {
      get { return _no_peers; }
      set { _no_peers = value; }
    }
    private uint _last_report_time;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"last_report_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint last_report_time
    {
      get { return _last_report_time; }
      set { _last_report_time = value; }
    }
    private uint _last_activity;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"last_activity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint last_activity
    {
      get { return _last_activity; }
      set { _last_activity = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _participating_friends = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"participating_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> participating_friends
    {
      get { return _participating_friends; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _nicknames = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(11, Name=@"nicknames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> nicknames
    {
      get { return _nicknames; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LobbyState")]
    public enum LobbyState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOBBYSTATE_JOINED", Value=1)]
      LOBBYSTATE_JOINED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOBBYSTATE_INVITED", Value=2)]
      LOBBYSTATE_INVITED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOBBYSTATE_PUBLIC", Value=3)]
      LOBBYSTATE_PUBLIC = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatId")]
  public partial class ChatId : global::ProtoBuf.IExtensible
  {
    public ChatId() {}
    
    private rsctrl.chat.ChatType _chat_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.chat.ChatType chat_type
    {
      get { return _chat_type; }
      set { _chat_type = value; }
    }
    private string _chat_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chat_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string chat_id
    {
      get { return _chat_id; }
      set { _chat_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMessage")]
  public partial class ChatMessage : global::ProtoBuf.IExtensible
  {
    public ChatMessage() {}
    
    private rsctrl.chat.ChatId _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.chat.ChatId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }

    private string _peer_nickname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"peer_nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string peer_nickname
    {
      get { return _peer_nickname; }
      set { _peer_nickname = value; }
    }

    private uint _chat_flags = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chat_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chat_flags
    {
      get { return _chat_flags; }
      set { _chat_flags = value; }
    }

    private uint _send_time = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"send_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint send_time
    {
      get { return _send_time; }
      set { _send_time = value; }
    }

    private uint _recv_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"recv_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recv_time
    {
      get { return _recv_time; }
      set { _recv_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseChatLobbies")]
  public partial class ResponseChatLobbies : global::ProtoBuf.IExtensible
  {
    public ResponseChatLobbies() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.chat.ChatLobbyInfo> _lobbies = new global::System.Collections.Generic.List<rsctrl.chat.ChatLobbyInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"lobbies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.chat.ChatLobbyInfo> lobbies
    {
      get { return _lobbies; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestChatLobbies")]
  public partial class RequestChatLobbies : global::ProtoBuf.IExtensible
  {
    public RequestChatLobbies() {}
    
    private rsctrl.chat.RequestChatLobbies.LobbySet _lobby_set;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby_set", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.chat.RequestChatLobbies.LobbySet lobby_set
    {
      get { return _lobby_set; }
      set { _lobby_set = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LobbySet")]
    public enum LobbySet
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOBBYSET_ALL", Value=1)]
      LOBBYSET_ALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOBBYSET_JOINED", Value=2)]
      LOBBYSET_JOINED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOBBYSET_INVITED", Value=3)]
      LOBBYSET_INVITED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOBBYSET_PUBLIC", Value=4)]
      LOBBYSET_PUBLIC = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestCreateLobby")]
  public partial class RequestCreateLobby : global::ProtoBuf.IExtensible
  {
    public RequestCreateLobby() {}
    
    private string _lobby_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lobby_name
    {
      get { return _lobby_name; }
      set { _lobby_name = value; }
    }
    private string _lobby_topic;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lobby_topic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lobby_topic
    {
      get { return _lobby_topic; }
      set { _lobby_topic = value; }
    }
    private rsctrl.chat.LobbyPrivacyLevel _privacy_level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"privacy_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.chat.LobbyPrivacyLevel privacy_level
    {
      get { return _privacy_level; }
      set { _privacy_level = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _invited_friends = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"invited_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> invited_friends
    {
      get { return _invited_friends; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestJoinOrLeaveLobby")]
  public partial class RequestJoinOrLeaveLobby : global::ProtoBuf.IExtensible
  {
    public RequestJoinOrLeaveLobby() {}
    
    private string _lobby_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lobby_id
    {
      get { return _lobby_id; }
      set { _lobby_id = value; }
    }
    private rsctrl.chat.RequestJoinOrLeaveLobby.LobbyAction _action;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.chat.RequestJoinOrLeaveLobby.LobbyAction action
    {
      get { return _action; }
      set { _action = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LobbyAction")]
    public enum LobbyAction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN_OR_ACCEPT", Value=1)]
      JOIN_OR_ACCEPT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEAVE_OR_DENY", Value=2)]
      LEAVE_OR_DENY = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestSetLobbyNickname")]
  public partial class RequestSetLobbyNickname : global::ProtoBuf.IExtensible
  {
    public RequestSetLobbyNickname() {}
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _lobby_ids = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"lobby_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> lobby_ids
    {
      get { return _lobby_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseSetLobbyNickname")]
  public partial class ResponseSetLobbyNickname : global::ProtoBuf.IExtensible
  {
    public ResponseSetLobbyNickname() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestRegisterEvents")]
  public partial class RequestRegisterEvents : global::ProtoBuf.IExtensible
  {
    public RequestRegisterEvents() {}
    
    private rsctrl.chat.RequestRegisterEvents.RegisterAction _action;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.chat.RequestRegisterEvents.RegisterAction action
    {
      get { return _action; }
      set { _action = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RegisterAction")]
    public enum RegisterAction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER", Value=1)]
      REGISTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEREGISTER", Value=2)]
      DEREGISTER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseRegisterEvents")]
  public partial class ResponseRegisterEvents : global::ProtoBuf.IExtensible
  {
    public ResponseRegisterEvents() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EventLobbyInvite")]
  public partial class EventLobbyInvite : global::ProtoBuf.IExtensible
  {
    public EventLobbyInvite() {}
    
    private rsctrl.chat.ChatLobbyInfo _lobby;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.chat.ChatLobbyInfo lobby
    {
      get { return _lobby; }
      set { _lobby = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EventChatMessage")]
  public partial class EventChatMessage : global::ProtoBuf.IExtensible
  {
    public EventChatMessage() {}
    
    private rsctrl.chat.ChatMessage _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.chat.ChatMessage msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestSendMessage")]
  public partial class RequestSendMessage : global::ProtoBuf.IExtensible
  {
    public RequestSendMessage() {}
    
    private rsctrl.chat.ChatMessage _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.chat.ChatMessage msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseSendMessage")]
  public partial class ResponseSendMessage : global::ProtoBuf.IExtensible
  {
    public ResponseSendMessage() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RequestMsgIds")]
    public enum RequestMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestChatLobbies", Value=1)]
      MsgId_RequestChatLobbies = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestCreateLobby", Value=2)]
      MsgId_RequestCreateLobby = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestJoinOrLeaveLobby", Value=3)]
      MsgId_RequestJoinOrLeaveLobby = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestSetLobbyNickname", Value=4)]
      MsgId_RequestSetLobbyNickname = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestRegisterEvents", Value=5)]
      MsgId_RequestRegisterEvents = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestSendMessage", Value=6)]
      MsgId_RequestSendMessage = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResponseMsgIds")]
    public enum ResponseMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseChatLobbies", Value=1)]
      MsgId_ResponseChatLobbies = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseSetLobbyNickname", Value=4)]
      MsgId_ResponseSetLobbyNickname = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseRegisterEvents", Value=5)]
      MsgId_ResponseRegisterEvents = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseSendMessage", Value=6)]
      MsgId_ResponseSendMessage = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_EventLobbyInvite", Value=101)]
      MsgId_EventLobbyInvite = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_EventChatMessage", Value=102)]
      MsgId_EventChatMessage = 102
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LobbyPrivacyLevel")]
    public enum LobbyPrivacyLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRIVACY_PRIVATE", Value=1)]
      PRIVACY_PRIVATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRIVACY_PUBLIC", Value=2)]
      PRIVACY_PUBLIC = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChatType")]
    public enum ChatType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_PRIVATE", Value=1)]
      TYPE_PRIVATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_LOBBY", Value=2)]
      TYPE_LOBBY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_GROUP", Value=3)]
      TYPE_GROUP = 3
    }
  
}