//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: files.proto
// Note: requires additional types generated from: core.proto
namespace rsctrl.files
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileTransfer")]
  public partial class FileTransfer : global::ProtoBuf.IExtensible
  {
    public FileTransfer() {}
    
    private rsctrl.core.File _file;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"file", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.File file
    {
      get { return _file; }
      set { _file = value; }
    }
    private rsctrl.files.Direction _direction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.files.Direction direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private float _fraction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fraction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float fraction
    {
      get { return _fraction; }
      set { _fraction = value; }
    }
    private float _rate_kBs;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rate_kBs", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rate_kBs
    {
      get { return _rate_kBs; }
      set { _rate_kBs = value; }
    }
    private rsctrl.files.TransferState _state;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.files.TransferState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestTransferList")]
  public partial class RequestTransferList : global::ProtoBuf.IExtensible
  {
    public RequestTransferList() {}
    
    private rsctrl.files.Direction _direction;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.files.Direction direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseTransferList")]
  public partial class ResponseTransferList : global::ProtoBuf.IExtensible
  {
    public ResponseTransferList() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.files.FileTransfer> _transfers = new global::System.Collections.Generic.List<rsctrl.files.FileTransfer>();
    [global::ProtoBuf.ProtoMember(2, Name=@"transfers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.files.FileTransfer> transfers
    {
      get { return _transfers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestControlDownload")]
  public partial class RequestControlDownload : global::ProtoBuf.IExtensible
  {
    public RequestControlDownload() {}
    
    private rsctrl.core.File _file;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"file", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.File file
    {
      get { return _file; }
      set { _file = value; }
    }
    private rsctrl.files.RequestControlDownload.Action _action;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.files.RequestControlDownload.Action action
    {
      get { return _action; }
      set { _action = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Action")]
    public enum Action
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION_START", Value=1)]
      ACTION_START = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION_CONTINUE", Value=2)]
      ACTION_CONTINUE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION_WAIT", Value=3)]
      ACTION_WAIT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION_PAUSE", Value=4)]
      ACTION_PAUSE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION_RESTART", Value=5)]
      ACTION_RESTART = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION_CHECK", Value=6)]
      ACTION_CHECK = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION_CANCEL", Value=7)]
      ACTION_CANCEL = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseControlDownload")]
  public partial class ResponseControlDownload : global::ProtoBuf.IExtensible
  {
    public ResponseControlDownload() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestShareDirList")]
  public partial class RequestShareDirList : global::ProtoBuf.IExtensible
  {
    public RequestShareDirList() {}
    
    private string _ssl_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ssl_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ssl_id
    {
      get { return _ssl_id; }
      set { _ssl_id = value; }
    }
    private string _path;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseShareDirList")]
  public partial class ResponseShareDirList : global::ProtoBuf.IExtensible
  {
    public ResponseShareDirList() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _ssl_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ssl_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ssl_id
    {
      get { return _ssl_id; }
      set { _ssl_id = value; }
    }
    private string _path;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private rsctrl.files.ResponseShareDirList.ListType _list_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"list_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rsctrl.files.ResponseShareDirList.ListType list_type
    {
      get { return _list_type; }
      set { _list_type = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.core.File> _files = new global::System.Collections.Generic.List<rsctrl.core.File>();
    [global::ProtoBuf.ProtoMember(5, Name=@"files", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.core.File> files
    {
      get { return _files; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ListType")]
    public enum ListType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIRQUERY_ROOT", Value=1)]
      DIRQUERY_ROOT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIRQUERY_PERSON", Value=2)]
      DIRQUERY_PERSON = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIRQUERY_FILE", Value=3)]
      DIRQUERY_FILE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIRQUERY_DIR", Value=4)]
      DIRQUERY_DIR = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RequestMsgIds")]
    public enum RequestMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestTransferList", Value=1)]
      MsgId_RequestTransferList = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestControlDownload", Value=2)]
      MsgId_RequestControlDownload = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestShareDirList", Value=3)]
      MsgId_RequestShareDirList = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResponseMsgIds")]
    public enum ResponseMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseTransferList", Value=1)]
      MsgId_ResponseTransferList = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseControlDownload", Value=2)]
      MsgId_ResponseControlDownload = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseShareDirList", Value=3)]
      MsgId_ResponseShareDirList = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Direction")]
    public enum Direction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIRECTION_UPLOAD", Value=1)]
      DIRECTION_UPLOAD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIRECTION_DOWNLOAD", Value=2)]
      DIRECTION_DOWNLOAD = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TransferState")]
    public enum TransferState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFER_FAILED", Value=1)]
      TRANSFER_FAILED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFER_OKAY", Value=2)]
      TRANSFER_OKAY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFER_PAUSED", Value=3)]
      TRANSFER_PAUSED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFER_QUEUED", Value=4)]
      TRANSFER_QUEUED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFER_WAITING", Value=5)]
      TRANSFER_WAITING = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFER_DOWNLOADING", Value=6)]
      TRANSFER_DOWNLOADING = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFER_CHECKING_HASH", Value=7)]
      TRANSFER_CHECKING_HASH = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFER_COMPLETE", Value=8)]
      TRANSFER_COMPLETE = 8
    }
  
}