//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gxs.proto
// Note: requires additional types generated from: core.proto
namespace rsctrl.gxs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Service")]
  public partial class Service : global::ProtoBuf.IExtensible
  {
    public Service() {}
    
    private uint _service_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint service_id
    {
      get { return _service_id; }
      set { _service_id = value; }
    }

    private string _service_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"service_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string service_name
    {
      get { return _service_name; }
      set { _service_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupMeta")]
  public partial class GroupMeta : global::ProtoBuf.IExtensible
  {
    public GroupMeta() {}
    
    private string _group_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private string _group_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"group_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string group_name
    {
      get { return _group_name; }
      set { _group_name = value; }
    }
    private uint _group_flags;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"group_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint group_flags
    {
      get { return _group_flags; }
      set { _group_flags = value; }
    }
    private uint _sign_flags;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sign_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sign_flags
    {
      get { return _sign_flags; }
      set { _sign_flags = value; }
    }
    private uint _publish_ts;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"publish_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint publish_ts
    {
      get { return _publish_ts; }
      set { _publish_ts = value; }
    }

    private string _author_id = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"author_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string author_id
    {
      get { return _author_id; }
      set { _author_id = value; }
    }
    private uint _subscribe_flags;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"subscribe_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subscribe_flags
    {
      get { return _subscribe_flags; }
      set { _subscribe_flags = value; }
    }
    private uint _group_status;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"group_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint group_status
    {
      get { return _group_status; }
      set { _group_status = value; }
    }

    private string _service_string = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"service_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string service_string
    {
      get { return _service_string; }
      set { _service_string = value; }
    }

    private uint _pop = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pop
    {
      get { return _pop; }
      set { _pop = value; }
    }

    private uint _msg_count = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"msg_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint msg_count
    {
      get { return _msg_count; }
      set { _msg_count = value; }
    }

    private int _last_post = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"last_post", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int last_post
    {
      get { return _last_post; }
      set { _last_post = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"GroupFlags")]
    public enum GroupFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GF_FLAG1", Value=1)]
      GF_FLAG1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GF_FLAG2", Value=2)]
      GF_FLAG2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GF_FLAG3", Value=4)]
      GF_FLAG3 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GF_FLAG4", Value=8)]
      GF_FLAG4 = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SignFlags")]
    public enum SignFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SF_FLAG1", Value=1)]
      SF_FLAG1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SF_FLAG2", Value=2)]
      SF_FLAG2 = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SubscribeFlags")]
    public enum SubscribeFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUBF_FLAG1", Value=1)]
      SUBF_FLAG1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUBF_FLAG2", Value=2)]
      SUBF_FLAG2 = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"StatusFlags")]
    public enum StatusFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATF_FLAG1", Value=1)]
      STATF_FLAG1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATF_FLAG2", Value=2)]
      STATF_FLAG2 = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupGenericData")]
  public partial class GroupGenericData : global::ProtoBuf.IExtensible
  {
    public GroupGenericData() {}
    
    private rsctrl.gxs.GroupMeta _meta;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.GroupMeta meta
    {
      get { return _meta; }
      set { _meta = value; }
    }
    private string _encoded_data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"encoded_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string encoded_data
    {
      get { return _encoded_data; }
      set { _encoded_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgMeta")]
  public partial class MsgMeta : global::ProtoBuf.IExtensible
  {
    public MsgMeta() {}
    
    private string _group_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private string _msg_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg_id
    {
      get { return _msg_id; }
      set { _msg_id = value; }
    }
    private string _thread_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"thread_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string thread_id
    {
      get { return _thread_id; }
      set { _thread_id = value; }
    }
    private uint _parent_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"parent_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint parent_id
    {
      get { return _parent_id; }
      set { _parent_id = value; }
    }
    private uint _origmsg_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"origmsg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint origmsg_id
    {
      get { return _origmsg_id; }
      set { _origmsg_id = value; }
    }

    private string _author_id = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"author_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string author_id
    {
      get { return _author_id; }
      set { _author_id = value; }
    }
    private uint _publish_ts;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"publish_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint publish_ts
    {
      get { return _publish_ts; }
      set { _publish_ts = value; }
    }
    private uint _msg_name;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"msg_name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msg_name
    {
      get { return _msg_name; }
      set { _msg_name = value; }
    }
    private uint _msg_flags;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"msg_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msg_flags
    {
      get { return _msg_flags; }
      set { _msg_flags = value; }
    }
    private uint _msg_status;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"msg_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msg_status
    {
      get { return _msg_status; }
      set { _msg_status = value; }
    }
    private uint _child_ts;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"child_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint child_ts
    {
      get { return _child_ts; }
      set { _child_ts = value; }
    }

    private string _service_string = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"service_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string service_string
    {
      get { return _service_string; }
      set { _service_string = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"GroupFlags")]
    public enum GroupFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GF_FLAG1", Value=1)]
      GF_FLAG1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GF_FLAG2", Value=2)]
      GF_FLAG2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GF_FLAG3", Value=4)]
      GF_FLAG3 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GF_FLAG4", Value=8)]
      GF_FLAG4 = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SignFlags")]
    public enum SignFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SF_FLAG1", Value=1)]
      SF_FLAG1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SF_FLAG2", Value=2)]
      SF_FLAG2 = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SubscribeFlags")]
    public enum SubscribeFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUBF_FLAG1", Value=1)]
      SUBF_FLAG1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUBF_FLAG2", Value=2)]
      SUBF_FLAG2 = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"StatusFlags")]
    public enum StatusFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATF_FLAG1", Value=1)]
      STATF_FLAG1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATF_FLAG2", Value=2)]
      STATF_FLAG2 = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGenericData")]
  public partial class MsgGenericData : global::ProtoBuf.IExtensible
  {
    public MsgGenericData() {}
    
    private rsctrl.gxs.MsgMeta _meta;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.MsgMeta meta
    {
      get { return _meta; }
      set { _meta = value; }
    }
    private string _encoded_data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"encoded_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string encoded_data
    {
      get { return _encoded_data; }
      set { _encoded_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Filter")]
  public partial class Filter : global::ProtoBuf.IExtensible
  {
    public Filter() {}
    
    private uint _options;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint options
    {
      get { return _options; }
      set { _options = value; }
    }

    private uint _status_filter = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status_filter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status_filter
    {
      get { return _status_filter; }
      set { _status_filter = value; }
    }

    private uint _status_mask = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status_mask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status_mask
    {
      get { return _status_mask; }
      set { _status_mask = value; }
    }

    private uint _req_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"req_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint req_type
    {
      get { return _req_type; }
      set { _req_type = value; }
    }

    private uint _subscribe_filter = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"subscribe_filter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint subscribe_filter
    {
      get { return _subscribe_filter; }
      set { _subscribe_filter = value; }
    }

    private int _before = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"before", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int before
    {
      get { return _before; }
      set { _before = value; }
    }

    private int _after = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"after", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int after
    {
      get { return _after; }
      set { _after = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSet")]
  public partial class MsgSet : global::ProtoBuf.IExtensible
  {
    public MsgSet() {}
    
    private string _group_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _msg_id = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"msg_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> msg_id
    {
      get { return _msg_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupMsgSet")]
  public partial class GroupMsgSet : global::ProtoBuf.IExtensible
  {
    public GroupMsgSet() {}
    
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.MsgSet> _groups = new global::System.Collections.Generic.List<rsctrl.gxs.MsgSet>();
    [global::ProtoBuf.ProtoMember(1, Name=@"groups", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.MsgSet> groups
    {
      get { return _groups; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestGroupInfo")]
  public partial class RequestGroupInfo : global::ProtoBuf.IExtensible
  {
    public RequestGroupInfo() {}
    
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private uint _ans_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ans_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ans_type
    {
      get { return _ans_type; }
      set { _ans_type = value; }
    }
    private rsctrl.gxs.Filter _options;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Filter options
    {
      get { return _options; }
      set { _options = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _group_ids = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"group_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> group_ids
    {
      get { return _group_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseGroupList")]
  public partial class ResponseGroupList : global::ProtoBuf.IExtensible
  {
    public ResponseGroupList() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _group_ids = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"group_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> group_ids
    {
      get { return _group_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseGroupMeta")]
  public partial class ResponseGroupMeta : global::ProtoBuf.IExtensible
  {
    public ResponseGroupMeta() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.GroupMeta> _meta = new global::System.Collections.Generic.List<rsctrl.gxs.GroupMeta>();
    [global::ProtoBuf.ProtoMember(3, Name=@"meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.GroupMeta> meta
    {
      get { return _meta; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseGroupData")]
  public partial class ResponseGroupData : global::ProtoBuf.IExtensible
  {
    public ResponseGroupData() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.GroupGenericData> _data = new global::System.Collections.Generic.List<rsctrl.gxs.GroupGenericData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.GroupGenericData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestMsgInfo")]
  public partial class RequestMsgInfo : global::ProtoBuf.IExtensible
  {
    public RequestMsgInfo() {}
    
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private uint _ans_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ans_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ans_type
    {
      get { return _ans_type; }
      set { _ans_type = value; }
    }
    private rsctrl.gxs.Filter _options;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Filter options
    {
      get { return _options; }
      set { _options = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet> _msgs = new global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet>();
    [global::ProtoBuf.ProtoMember(4, Name=@"msgs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet> msgs
    {
      get { return _msgs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestMsgRelatedInfo")]
  public partial class RequestMsgRelatedInfo : global::ProtoBuf.IExtensible
  {
    public RequestMsgRelatedInfo() {}
    
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private uint _ans_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ans_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ans_type
    {
      get { return _ans_type; }
      set { _ans_type = value; }
    }
    private rsctrl.gxs.Filter _options;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Filter options
    {
      get { return _options; }
      set { _options = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet> _msgs = new global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet>();
    [global::ProtoBuf.ProtoMember(4, Name=@"msgs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet> msgs
    {
      get { return _msgs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseMsgList")]
  public partial class ResponseMsgList : global::ProtoBuf.IExtensible
  {
    public ResponseMsgList() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet> _msgs = new global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet>();
    [global::ProtoBuf.ProtoMember(3, Name=@"msgs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.GroupMsgSet> msgs
    {
      get { return _msgs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseMsgMeta")]
  public partial class ResponseMsgMeta : global::ProtoBuf.IExtensible
  {
    public ResponseMsgMeta() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.MsgMeta> _meta = new global::System.Collections.Generic.List<rsctrl.gxs.MsgMeta>();
    [global::ProtoBuf.ProtoMember(3, Name=@"meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.MsgMeta> meta
    {
      get { return _meta; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseMsgData")]
  public partial class ResponseMsgData : global::ProtoBuf.IExtensible
  {
    public ResponseMsgData() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.MsgGenericData> _data = new global::System.Collections.Generic.List<rsctrl.gxs.MsgGenericData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.MsgGenericData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestCreateGroup")]
  public partial class RequestCreateGroup : global::ProtoBuf.IExtensible
  {
    public RequestCreateGroup() {}
    
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.GroupGenericData> _data = new global::System.Collections.Generic.List<rsctrl.gxs.GroupGenericData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.GroupGenericData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestCreateMsg")]
  public partial class RequestCreateMsg : global::ProtoBuf.IExtensible
  {
    public RequestCreateMsg() {}
    
    private rsctrl.gxs.Service _service;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.gxs.Service service
    {
      get { return _service; }
      set { _service = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.gxs.MsgGenericData> _data = new global::System.Collections.Generic.List<rsctrl.gxs.MsgGenericData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.gxs.MsgGenericData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RequestMsgIds")]
    public enum RequestMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestPeers", Value=1)]
      MsgId_RequestPeers = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestAddPeer", Value=2)]
      MsgId_RequestAddPeer = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestModifyPeer", Value=3)]
      MsgId_RequestModifyPeer = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResponseMsgIds")]
    public enum ResponseMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponsePeerList", Value=1)]
      MsgId_ResponsePeerList = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseAddPeer", Value=2)]
      MsgId_ResponseAddPeer = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseModifyPeer", Value=3)]
      MsgId_ResponseModifyPeer = 3
    }
  
}