//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: search.proto
// Note: requires additional types generated from: core.proto
namespace rsctrl.search
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchHit")]
  public partial class SearchHit : global::ProtoBuf.IExtensible
  {
    public SearchHit() {}
    
    private rsctrl.core.File _file;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"file", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.File file
    {
      get { return _file; }
      set { _file = value; }
    }
    private uint _loc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"loc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint loc
    {
      get { return _loc; }
      set { _loc = value; }
    }
    private uint _no_hits;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"no_hits", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint no_hits
    {
      get { return _no_hits; }
      set { _no_hits = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LocFlag")]
    public enum LocFlag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCAL", Value=1)]
      LOCAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND", Value=2)]
      FRIEND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NETWORK", Value=4)]
      NETWORK = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchSet")]
  public partial class SearchSet : global::ProtoBuf.IExtensible
  {
    public SearchSet() {}
    
    private uint _search_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"search_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint search_id
    {
      get { return _search_id; }
      set { _search_id = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.search.SearchHit> _hits = new global::System.Collections.Generic.List<rsctrl.search.SearchHit>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.search.SearchHit> hits
    {
      get { return _hits; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestBasicSearch")]
  public partial class RequestBasicSearch : global::ProtoBuf.IExtensible
  {
    public RequestBasicSearch() {}
    
    private readonly global::System.Collections.Generic.List<string> _terms = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"terms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> terms
    {
      get { return _terms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestAdvSearch")]
  public partial class RequestAdvSearch : global::ProtoBuf.IExtensible
  {
    public RequestAdvSearch() {}
    
    private readonly global::System.Collections.Generic.List<string> _terms = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"terms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> terms
    {
      get { return _terms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseSearchIds")]
  public partial class ResponseSearchIds : global::ProtoBuf.IExtensible
  {
    public ResponseSearchIds() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _search_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"search_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> search_id
    {
      get { return _search_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestCloseSearch")]
  public partial class RequestCloseSearch : global::ProtoBuf.IExtensible
  {
    public RequestCloseSearch() {}
    
    private uint _search_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"search_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint search_id
    {
      get { return _search_id; }
      set { _search_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestListSearches")]
  public partial class RequestListSearches : global::ProtoBuf.IExtensible
  {
    public RequestListSearches() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestSearchResults")]
  public partial class RequestSearchResults : global::ProtoBuf.IExtensible
  {
    public RequestSearchResults() {}
    
    private readonly global::System.Collections.Generic.List<uint> _search_ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"search_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> search_ids
    {
      get { return _search_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseSearchResults")]
  public partial class ResponseSearchResults : global::ProtoBuf.IExtensible
  {
    public ResponseSearchResults() {}
    
    private rsctrl.core.Status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public rsctrl.core.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<rsctrl.search.SearchSet> _searches = new global::System.Collections.Generic.List<rsctrl.search.SearchSet>();
    [global::ProtoBuf.ProtoMember(2, Name=@"searches", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rsctrl.search.SearchSet> searches
    {
      get { return _searches; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RequestMsgIds")]
    public enum RequestMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestBasicSearch", Value=1)]
      MsgId_RequestBasicSearch = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestCloseSearch", Value=3)]
      MsgId_RequestCloseSearch = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestListSearches", Value=4)]
      MsgId_RequestListSearches = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_RequestSearchResults", Value=5)]
      MsgId_RequestSearchResults = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResponseMsgIds")]
    public enum ResponseMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseSearchIds", Value=1)]
      MsgId_ResponseSearchIds = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgId_ResponseSearchResults", Value=5)]
      MsgId_ResponseSearchResults = 5
    }
  
}